const fs = require('fs');
const filePath = 'src/data/sarkariYojanaServicesData.ts';
let content = fs.readFileSync(filePath, 'utf-8');

const newItems = `  {
    id: 'fr-1',
    name: 'Farmer Registry Registration',
    hindiName: 'किसान रजिस्ट्री पंजीकरण',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Register as a new farmer on the official UP Agristack portal.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'पंजीकरण करें',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['farmer registry', 'किसान रजिस्ट्री', 'किसान रजिस्ट्रेशन', 'agristack', 'up farmer registry', 'किसान पंजीकरण'],
    isCentral: false,
    state: 'UP State',
    isPopular: true
  },
  {
    id: 'fr-2',
    name: 'Farmer Registry Status',
    hindiName: 'पंजीकरण की स्थिति',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Check the live status of your Farmer Registry application.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'स्थिति देखें',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'पंजीकरण करें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['farmer registry status', 'किसान रजिस्ट्री', 'स्थिति', 'agristack'],
    isCentral: false,
    state: 'UP State'
  },
  {
    id: 'fr-3',
    name: 'Farmer ID / Registration Details',
    hindiName: 'किसान आईडी / विवरण',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Search and download your official Farmer ID and registration details.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'Farmer ID',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['farmer id', 'किसान आईडी', 'किसान रजिस्ट्रेशन', 'agristack'],
    isCentral: false,
    state: 'UP State'
  },
  {
    id: 'fr-4',
    name: 'Farmer Details',
    hindiName: 'किसान का विवरण',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'View comprehensive farmer details and demographic information.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'विवरण देखें',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['farmer details', 'किसान का विवरण', 'किसान रजिस्ट्री'],
    isCentral: false,
    state: 'UP State'
  },
  {
    id: 'fr-5',
    name: 'Land / Account Info',
    hindiName: 'भूमि/खाता संबंधी जानकारी',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Link and verify your land records (Bhulekh) and bank account details.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'भूमि जानकारी',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['land record', 'भूमि', 'खाता', 'किसान रजिस्ट्री', 'bhulekh', 'farmer registry'],
    isCentral: false,
    state: 'UP State'
  },
  {
    id: 'fr-6',
    name: 'e-KYC / Farmer Verification',
    hindiName: 'e-KYC / किसान सत्यापन',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Complete your Aadhaar based e-KYC for Farmer Registry.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'e-KYC करें',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['ekyc', 'e-kyc', 'किसान सत्यापन', 'farmer verification', 'agristack'],
    isCentral: false,
    state: 'UP State'
  },
  {
    id: 'fr-7',
    name: 'CSC Farmer Registry Service',
    hindiName: 'CSC से किसान रजिस्ट्री सेवा',
    category: '14. Kisan & Agriculture',
    department: 'UP Agriculture Dept / AgriStack',
    description: 'Login via CSC VLE to provide Farmer Registry services to citizens.',
    officialUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    actionText: 'CSC Login',
    statusCheckUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    statusText: 'स्थिति देखें',
    guidelinesUrl: 'https://upfr.agristack.gov.in/farmer-registry-up/',
    guidelineText: 'आधिकारिक पोर्टल',
    tags: ['csc', 'vle', 'csc farmer registry', 'agristack'],
    isCentral: false,
    state: 'UP State'
  },
`;

content = content.replace("  {\n    id: 'service-158',", newItems + "  {\n    id: 'service-158',");
fs.writeFileSync(filePath, content);
console.log("Done");
