import { Post, Category, Announcement, ComputerService, Advertisement, SiteSettings, PostComment, Promotion } from '../src/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Sarkari Naukri', slug: 'sarkari-naukri', type: 'job', displayOrder: 1, badgeColor: 'blue', enabled: true, iconName: 'Briefcase' },
  { id: 'cat-2', name: 'Latest Jobs', slug: 'latest-jobs', type: 'job', displayOrder: 2, badgeColor: 'blue', enabled: true, iconName: 'Sparkles' },
  { id: 'cat-3', name: 'New Recruitment', slug: 'new-recruitment', type: 'job', displayOrder: 3, badgeColor: 'indigo', enabled: true, iconName: 'FileText' },
  { id: 'cat-4', name: 'Admit Card', slug: 'admit-card', type: 'admit_card', displayOrder: 4, badgeColor: 'amber', enabled: true, iconName: 'CreditCard' },
  { id: 'cat-5', name: 'Sarkari Result', slug: 'result', type: 'result', displayOrder: 5, badgeColor: 'emerald', enabled: true, iconName: 'Award' },
  { id: 'cat-6', name: 'Answer Key', slug: 'answer-key', type: 'answer_key', displayOrder: 6, badgeColor: 'teal', enabled: true, iconName: 'Key' },
  { id: 'cat-7', name: 'Syllabus', slug: 'syllabus', type: 'syllabus', displayOrder: 7, badgeColor: 'purple', enabled: true, iconName: 'BookOpen' },
  { id: 'cat-8', name: 'Exam Date / City', slug: 'exam-date-city', type: 'exam_date', displayOrder: 8, badgeColor: 'rose', enabled: true, iconName: 'Calendar' },
  { id: 'cat-9', name: 'Admission', slug: 'admission', type: 'admission', displayOrder: 9, badgeColor: 'cyan', enabled: true, iconName: 'GraduationCap' },
  { id: 'cat-10', name: 'Scholarship', slug: 'scholarship', type: 'scholarship', displayOrder: 10, badgeColor: 'green', enabled: true, iconName: 'DollarSign' },
  { id: 'cat-11', name: 'Sarkari Yojana', slug: 'sarkari-yojana', type: 'sarkari_yojana', displayOrder: 11, badgeColor: 'red', enabled: true, iconName: 'HelpCircle' },
  { id: 'cat-12', name: 'Government Schemes', slug: 'government-schemes', type: 'sarkari_yojana', displayOrder: 12, badgeColor: 'red', enabled: true, iconName: 'Layers' },
  { id: 'cat-13', name: 'Online Forms', slug: 'online-forms', type: 'online_form', displayOrder: 13, badgeColor: 'blue', enabled: true, iconName: 'Edit3' },
  { id: 'cat-14', name: 'Important Notices', slug: 'important-notices', type: 'notice', displayOrder: 14, badgeColor: 'orange', enabled: true, iconName: 'Bell' },
  { id: 'cat-15', name: 'Career & Education', slug: 'career-education', type: 'job', displayOrder: 15, badgeColor: 'sky', enabled: true, iconName: 'TrendingUp' },
  { id: 'cat-16', name: 'Computer Center Services', slug: 'services', type: 'job', displayOrder: 16, badgeColor: 'violet', enabled: true, iconName: 'Monitor' },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    text: '⚡ SSC CGL 2026 Notification Out: 14,582 Group B & C Vacancies — Apply Online before Last Date!',
    link: '/jobs/ssc-cgl-recruitment-2026',
    isPinned: true,
    badge: 'HOT UPDATE',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ann-2',
    text: '📢 UP Police Constable 2026 Re-Exam Admit Card & City Slip Download Link Active Now!',
    link: '/admit-card/up-police-constable-admit-card-2026',
    isPinned: true,
    badge: 'ADMIT CARD',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ann-3',
    text: '🎯 UPSC Civil Services IAS / IFS Prelims 2026 Online Form Re-opened — Check Eligibility & Dates',
    link: '/jobs/upsc-civil-services-ias-2026',
    isPinned: false,
    badge: 'NEW JOB',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ann-4',
    text: '💰 PM Kisan Samman Nidhi 19th Installment e-KYC & Beneficiary Status Link Active Check Online',
    link: '/sarkari-yojana/pm-kisan-samman-nidhi-2026',
    isPinned: false,
    badge: 'YOJANA',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SERVICES: ComputerService[] = [
  {
    id: 'srv-1',
    name: 'Online Government & Job Form Filling',
    icon: 'FileText',
    description: 'Expert error-free application form filling for SSC, UPSC, Railway, UP Police, Banking, Teaching & State Exams with proper photo-signature resizing.',
    turnaroundTime: '10 - 20 Minutes',
    requiredDocs: ['Aadhaar Card', 'Passport Size Photo', 'Signature', 'Educational Marksheets (10th/12th/Graduation)', 'Caste Certificate (if applicable)'],
    feeRange: '₹50 - ₹100 per form',
    isPopular: true,
    enabled: true,
  },
  {
    id: 'srv-2',
    name: 'High-Speed Color & B/W Printouts / Photocopy',
    icon: 'Printer',
    description: 'Crisp, high-resolution laser printing for Admit Cards, Application Confirmation Pages, Resumes, Notes and Legal Documents.',
    turnaroundTime: 'Instant / 2 Minutes',
    requiredDocs: ['PDF / Document file via WhatsApp or Pendrive'],
    feeRange: '₹2 - ₹10 per page',
    isPopular: true,
    enabled: true,
  },
  {
    id: 'srv-3',
    name: 'Professional Resume & CV Making',
    icon: 'UserCheck',
    description: 'Modern, ATS-friendly biodata, freshers & experienced professional resumes with custom formatting and instant PDF + Print export.',
    turnaroundTime: '15 - 30 Minutes',
    requiredDocs: ['Personal details', 'Educational history', 'Work experience (if any)', 'Skills & Photo'],
    feeRange: '₹50 - ₹150',
    isPopular: true,
    enabled: true,
  },
  {
    id: 'srv-4',
    name: 'Urgent Passport Size Photo (Instant 5 Mins)',
    icon: 'Camera',
    description: 'Studio quality passport size photos with white, blue or light background tailored for Sarkari exams and official documents.',
    turnaroundTime: '5 Minutes',
    requiredDocs: ['In-person visit for photo click or clear digital selfie'],
    feeRange: '₹40 (8 Photos) / ₹70 (16 Photos)',
    isPopular: true,
    enabled: true,
  },
  {
    id: 'srv-5',
    name: 'PAN Card Apply, Correction & Instant e-PAN',
    icon: 'CreditCard',
    description: 'New PAN card application via NSDL / UTIITSL, Minor to Major update, Name/DOB corrections and instant e-PAN generation.',
    turnaroundTime: '2 - 3 Days (e-PAN in 2 hours)',
    requiredDocs: ['Aadhaar Card with linked Mobile Number', '2 Passport Photos', 'Signature'],
    feeRange: '₹120 - ₹150',
    isPopular: false,
    enabled: true,
  },
  {
    id: 'srv-6',
    name: 'Aadhaar Download, PVC Card Order & Print',
    icon: 'ShieldCheck',
    description: 'Original high-security waterproof Plastic PVC Aadhaar card direct delivery assistance and masked e-Aadhaar color laminations.',
    turnaroundTime: 'Instant Download / 7 Days PVC Delivery',
    requiredDocs: ['Aadhaar Number & OTP on registered mobile'],
    feeRange: '₹30 - ₹70',
    isPopular: false,
    enabled: true,
  },
  {
    id: 'srv-7',
    name: 'UP Scholarship & National Scholarship (NSP) Apply',
    icon: 'GraduationCap',
    description: 'Complete Pre-Matric, Post-Matric and Dashmottar Scholarship online registration, income/caste verification and final submission print.',
    turnaroundTime: '20 - 30 Minutes',
    requiredDocs: ['College Fee Receipt', 'Income Certificate', 'Caste Certificate', 'Bank Passbook', 'Marksheet', 'Aadhaar Card'],
    feeRange: '₹80 - ₹120',
    isPopular: true,
    enabled: true,
  },
  {
    id: 'srv-8',
    name: 'Document Scanning, PDF Merging & Compression',
    icon: 'FileSpreadsheet',
    description: 'Strict MB/KB size limit compliance document conversion, high-DPI scans, JPEG to PDF and certificate compression.',
    turnaroundTime: 'Instant',
    requiredDocs: ['Original physical documents'],
    feeRange: '₹10 - ₹30',
    isPopular: false,
    enabled: true,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    slug: 'ssc-cgl-recruitment-2026',
    type: 'job',
    title: 'SSC CGL 2026 Notification, Apply Online for 14,582 Group B & C Posts',
    shortDescription: 'Staff Selection Commission (SSC) has released Combined Graduate Level (CGL) Examination 2026 for 14,582 Assistant Section Officer, Income Tax Inspector, GST Inspector, Sub-Inspector and other Group B & C Vacancies.',
    category: 'SSC Jobs',
    department: 'Staff Selection Commission (SSC)',
    organization: 'Government of India',
    state: 'All India',
    status: 'published',
    isFeatured: true,
    isPinned: true,
    startDate: '2026-06-15',
    lastDate: '2026-09-30',
    feeLastDate: '2026-10-01',
    correctionDate: '2026-10-05',
    examDate: '2026-11-15',
    admitCardDate: '2026-11-05',
    resultDate: '2027-01-20',
    totalVacancy: '14,582 Posts',
    vacancies: [
      { id: 'v1', postName: 'Assistant Section Officer (CSS / MEA / IB)', total: 2450, general: 1100, obc: 650, ews: 240, sc: 300, st: 160, qualification: 'Bachelor Degree in any stream from recognized University' },
      { id: 'v2', postName: 'Inspector (Central Excise / GST / Preventive Officer)', total: 3820, general: 1720, obc: 980, ews: 380, sc: 490, st: 250, qualification: 'Bachelor Degree in any stream with physical fitness standard' },
      { id: 'v3', postName: 'Assistant Audit Officer / Assistant Accounts Officer (AAO)', total: 680, general: 310, obc: 180, ews: 68, sc: 82, st: 40, qualification: 'Bachelor Degree; CA / CMA / M.Com desirable' },
      { id: 'v4', postName: 'Executive Assistant / Tax Assistant / Sub Inspector (CBI/NIA)', total: 4200, general: 1900, obc: 1120, ews: 420, sc: 510, st: 250, qualification: 'Graduation in Any Subject + Computer Data Entry Proficiency' },
      { id: 'v5', postName: 'Auditor / Accountant / Junior Accountant', total: 3432, general: 1540, obc: 920, ews: 340, sc: 430, st: 202, qualification: 'Bachelor Degree in Any Stream' }
    ],
    feeStructure: {
      general: '₹100/-',
      obc: '₹100/-',
      ews: '₹100/-',
      sc: '₹0/- (Exempted)',
      st: '₹0/- (Exempted)',
      female: '₹0/- (Exempted)',
      phOrOther: '₹0/- (Exempted)',
      paymentMode: 'Net Banking, UPI, Credit/Debit Card or SBI Challan'
    },
    ageLimit: {
      minAge: '18 Years',
      maxAge: '27 - 32 Years (Post Wise)',
      asOnDate: '01/08/2026',
      ageRelaxation: 'OBC: 3 Years | SC/ST: 5 Years | PwD: 10 Years | Ex-Serviceman as per central government norms'
    },
    educationalQualification: 'Candidates must possess a Bachelor’s Degree in any discipline from a recognized University/Institute in India as on or before the closing date.',
    selectionProcess: [
      'Tier-I Computer Based Test (CBT - Qualifying)',
      'Tier-II Computer Based Examination (Paper-I Compulsory for all, Paper-II for JSO, Paper-III for AAO)',
      'Data Entry Speed Test (DEST) & Computer Knowledge Module',
      'Document Verification (DV) by User Departments',
      'Final Merit List'
    ],
    salaryPayScale: 'Pay Level-4 (₹25,500 - ₹81,100) to Pay Level-8 (₹47,600 - ₹1,51,100) + DA, HRA, TA and other allowances',
    examPattern: 'Tier-I consists of 100 Objective MCQs (200 Marks) spanning General Intelligence & Reasoning (25 Q), General Awareness (25 Q), Quantitative Aptitude (25 Q), and English Comprehension (25 Q). Time duration: 60 minutes. Negative marking: 0.50 marks per wrong answer.',
    syllabus: 'Detailed syllabus includes Arithmetic, Algebra, Geometry, Trigonometry, Current Affairs, Indian History & Polity, General Science, Grammar, Comprehension, and Reasoning abilities.',
    requiredDocuments: [
      'Recent Passport Size Color Photo (Live WebCam / Clean JPG with white background)',
      'Signature on white paper with black pen (10 to 20 KB)',
      '10th Class Marksheet / Matriculation Certificate (for DOB verification)',
      '12th Marksheet & Graduation Degree / Provisional Certificate',
      'Category Certificate (EWS / OBC-NCL / SC / ST valid format)',
      'Photo ID (Aadhaar Card, Voter ID, Passport, PAN Card)'
    ],
    importantInstructions: [
      'Candidates must register first on the new SSC One Time Registration (OTR) portal before applying.',
      'Live photograph will be captured through SSC App or Web camera. Ensure no caps, spectacles or masks are worn.',
      'Double check all personal details including Name, Father Name and Date of Birth as written in 10th certificate.',
      'Save the final submitted application form PDF and payment receipt for future reference.'
    ],
    importantLinks: [
      { id: 'l1', name: 'Apply Online (SSC OTR Portal)', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'apply', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 342 },
      { id: 'l2', name: 'Download Official Notification PDF', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'notification', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 215 },
      { id: 'l3', name: 'Download Syllabus & Exam Pattern', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'syllabus', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 120 },
      { id: 'l4', name: 'Official SSC Website', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 95 },
    ],
    officialSource: {
      websiteName: 'Staff Selection Commission (SSC Official Portal)',
      websiteUrl: 'https://ssc.gov.in',
      notificationUrl: 'https://ssc.gov.in',
      disclaimer: 'This information is compiled for informational convenience. Please verify all terms with the official notification published by SSC.'
    },
    seoTitle: 'SSC CGL 2026 Notification Out — Apply Online for 14582 Posts at ssc.gov.in',
    metaDescription: 'SSC CGL 2026 Online Application Form, Eligibility, Total Vacancy 14582, Exam Date, Syllabus, Age Limit & Important Dates at Shahnawaz Computer Center.',
    keywords: ['SSC CGL 2026', 'SSC Recruitment 2026', 'Staff Selection Commission', 'Sarkari Naukri', 'Apply Online SSC'],
    views: 4890,
    createdAt: '2026-06-15T09:00:00.000Z',
    updatedAt: '2026-08-20T10:30:00.000Z'
  },
  {
    id: 'post-2',
    slug: 'up-police-constable-admit-card-2026',
    type: 'admit_card',
    title: 'UP Police Constable Admit Card 2026 & Exam City Slip Released (60,244 Posts)',
    shortDescription: 'Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB), Lucknow has released the Exam City Intimation and Admit Card for 60,244 Constable Civil Police Direct Recruitment Examination.',
    category: 'Police Jobs',
    department: 'UPPRPB Lucknow',
    organization: 'Uttar Pradesh Police',
    state: 'Uttar Pradesh',
    status: 'published',
    isFeatured: true,
    isPinned: true,
    startDate: '2026-01-20',
    lastDate: '2026-02-28',
    examDate: '2026-09-05 to 2026-09-12',
    admitCardDate: '2026-08-28',
    resultDate: '2026-11-15',
    totalVacancy: '60,244 Posts',
    examCity: 'All 75 Districts of Uttar Pradesh',
    examCenterInfo: 'Candidates must report 2 hours prior to the exam shift. Biometric, Iris scan and Aadhaar authentication will be carried out at test centers.',
    requiredDocuments: [
      'Printed Color/B&W Copy of Admit Card',
      'Original Aadhaar Card / Voter ID / Driving License',
      'Black / Blue Ballpoint Pen',
      'Two recent passport-sized photographs'
    ],
    importantInstructions: [
      'Electronic gadgets, mobile phones, Bluetooth devices, smart watches, calculators and bags are strictly prohibited.',
      'Reach the examination center well before the gate closure time mentioned on the admit card.',
      'Check your roll number, exam center address, shift timings, and reporting time carefully.'
    ],
    importantLinks: [
      { id: 'l1', name: 'Download UP Police Admit Card', btnText: 'CLICK HERE', url: 'https://uppbpb.gov.in', type: 'admit_card', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 512 },
      { id: 'l2', name: 'Check Exam District / City Slip', btnText: 'CLICK HERE', url: 'https://uppbpb.gov.in', type: 'status', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 420 },
      { id: 'l3', name: 'Download Exam Guidelines & Notice', btnText: 'CLICK HERE', url: 'https://uppbpb.gov.in', type: 'notification', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 180 },
      { id: 'l4', name: 'UPPRPB Official Website', btnText: 'CLICK HERE', url: 'https://uppbpb.gov.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 130 },
    ],
    officialSource: {
      websiteName: 'UPPRPB Official Portal',
      websiteUrl: 'https://uppbpb.gov.in',
      disclaimer: 'Candidates are advised to download their admit cards only from the official UPPRPB website.'
    },
    seoTitle: 'UP Police Constable Admit Card 2026 Released — Download Hall Ticket uppbpb.gov.in',
    metaDescription: 'Download UP Police Constable 60244 Posts Admit Card 2026, Exam City Intimation, Exam Dates and Shift Timings at Shahnawaz Computer Center.',
    keywords: ['UP Police Admit Card 2026', 'UPPRPB Constable Hall Ticket', 'UP Police Exam City', 'Sarkari Result UP Police'],
    views: 6240,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-22T14:15:00.000Z'
  },
  {
    id: 'post-3',
    slug: 'upsc-civil-services-ias-2026',
    type: 'job',
    title: 'UPSC Civil Services IAS / IFS 2026 Notification, Online Form for 1,150 Posts',
    shortDescription: 'Union Public Service Commission (UPSC) invites online applications for Civil Services Examination (CSE) 2026 and Indian Forest Service (IFS) for recruitment to IAS, IPS, IFS, IRS and Central Services.',
    category: 'Central Government Jobs',
    department: 'Union Public Service Commission (UPSC)',
    organization: 'Government of India',
    state: 'All India',
    status: 'published',
    isFeatured: true,
    startDate: '2026-02-14',
    lastDate: '2026-09-25',
    feeLastDate: '2026-09-25',
    correctionDate: '2026-10-02',
    examDate: '2026-10-25',
    admitCardDate: '2026-10-10',
    totalVacancy: '1,150 Posts',
    feeStructure: {
      general: '₹100/-',
      obc: '₹100/-',
      ews: '₹100/-',
      sc: '₹0/-',
      st: '₹0/-',
      female: '₹0/-',
      phOrOther: '₹0/-',
      paymentMode: 'Online Debit/Credit card, Net Banking, UPI or cash at SBI branch'
    },
    ageLimit: {
      minAge: '21 Years',
      maxAge: '32 Years',
      asOnDate: '01/08/2026',
      ageRelaxation: 'OBC: 3 Years (Max 9 Attempts), SC/ST: 5 Years (Unlimited Attempts), PwBD: 10 Years'
    },
    educationalQualification: 'A degree of any recognized University incorporated by an Act of the Central or State Legislature in India or equivalent qualification.',
    selectionProcess: [
      'Preliminary Examination (Objective Type - 2 Papers, 400 Marks)',
      'Main Examination (Written Descriptive - 9 Papers, 1750 Marks)',
      'Personality Test / Interview (275 Marks)',
      'Final All India Merit Ranking & Service Allocation'
    ],
    salaryPayScale: 'Junior Scale Level 10 (₹56,100) to Cabinet Secretary Level 18 (₹2,50,000) with apex government privileges',
    importantLinks: [
      { id: 'l1', name: 'Apply Online (UPSC OTR Portal)', btnText: 'CLICK HERE', url: 'https://upsconline.nic.in', type: 'apply', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 190 },
      { id: 'l2', name: 'Download Official UPSC Notification', btnText: 'CLICK HERE', url: 'https://upsc.gov.in', type: 'notification', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 145 },
      { id: 'l3', name: 'Download Previous Year Question Papers', btnText: 'CLICK HERE', url: 'https://upsc.gov.in', type: 'syllabus', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 88 },
      { id: 'l4', name: 'Official UPSC Website', btnText: 'CLICK HERE', url: 'https://upsc.gov.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 65 },
    ],
    officialSource: {
      websiteName: 'Union Public Service Commission (UPSC)',
      websiteUrl: 'https://upsc.gov.in',
      disclaimer: 'Official details available on upsc.gov.in and upsconline.nic.in'
    },
    views: 3120,
    createdAt: '2026-02-14T10:00:00.000Z',
    updatedAt: '2026-08-18T11:00:00.000Z'
  },
  {
    id: 'post-4',
    slug: 'railway-rrb-ntpc-recruitment-2026',
    type: 'job',
    title: 'Railway RRB NTPC Graduate & Under Graduate Recruitment 2026 (11,558 Posts)',
    shortDescription: 'Railway Recruitment Boards (RRB) Centrally Published Notification for 11,558 Non-Technical Popular Categories (NTPC) including Goods Train Manager, Station Master, Senior Clerk, Junior Account Assistant & Commercial Apprentice.',
    category: 'Railway Jobs',
    department: 'Ministry of Railways, Railway Recruitment Control Board',
    organization: 'Indian Railways (RRBs)',
    state: 'All India',
    status: 'published',
    startDate: '2026-07-01',
    lastDate: '2026-10-15',
    feeLastDate: '2026-10-16',
    examDate: '2026-12-10',
    totalVacancy: '11,558 Posts',
    feeStructure: {
      general: '₹500/- (₹400 refunded after appearing in CBT-1)',
      obc: '₹500/- (₹400 refunded after appearing in CBT-1)',
      ews: '₹500/- (₹400 refunded after appearing in CBT-1)',
      sc: '₹250/- (₹250 full refunded after appearing in CBT-1)',
      st: '₹250/- (₹250 full refunded after appearing in CBT-1)',
      female: '₹250/- (₹250 full refunded after appearing in CBT-1)',
      phOrOther: '₹250/- (₹250 full refunded after appearing in CBT-1)',
      paymentMode: 'Online Net Banking, UPI, Credit/Debit Card'
    },
    ageLimit: {
      minAge: '18 Years',
      maxAge: '33 - 36 Years (with 3 Years COVID/Special Relaxation)',
      asOnDate: '01/07/2026',
      ageRelaxation: 'OBC: 3 Years | SC/ST: 5 Years | PwBD: 10 Years'
    },
    educationalQualification: 'For Undergraduate Posts: 12th Pass (+2 Stage) with at least 50% marks. For Graduate Posts: University Degree in any discipline.',
    selectionProcess: [
      '1st Stage Computer Based Test (CBT-1 common for all)',
      '2nd Stage Computer Based Test (CBT-2 post level wise)',
      'Computer Based Aptitude Test (CBAT) for Station Master / Traffic Assistant',
      'Typing Skill Test (TST) for Clerical Posts',
      'Document Verification and Medical Examination'
    ],
    salaryPayScale: '7th CPC Pay Matrix Level 2 (₹19,900) to Level 6 (₹35,400) + Railway perks & pass',
    importantLinks: [
      { id: 'l1', name: 'Apply Online (RRB Apply Portal)', btnText: 'CLICK HERE', url: 'https://www.rrbapply.gov.in', type: 'apply', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 380 },
      { id: 'l2', name: 'Download CEN Official Notification', btnText: 'CLICK HERE', url: 'https://www.rrbapply.gov.in', type: 'notification', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 210 },
      { id: 'l3', name: 'Official RRB Regional Portals', btnText: 'CLICK HERE', url: 'https://indianrailways.gov.in', type: 'official', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 110 },
    ],
    officialSource: {
      websiteName: 'Railway Recruitment Boards (RRB)',
      websiteUrl: 'https://www.rrbapply.gov.in',
      disclaimer: 'Indian Railways official applications are hosted solely on rrbapply.gov.in'
    },
    views: 4190,
    createdAt: '2026-07-01T10:00:00.000Z',
    updatedAt: '2026-08-20T12:00:00.000Z'
  },
  {
    id: 'post-5',
    slug: 'ibps-po-cwe-xv-result-2026',
    type: 'result',
    title: 'IBPS PO Prelims Result 2026 Out, Check Probationary Officer Score Card & Cut Off',
    shortDescription: 'Institute of Banking Personnel Selection (IBPS) has declared the Online Preliminary Examination Result for CRP PO/MT-XV for recruitment in 11 Participating Public Sector Banks.',
    category: 'Banking Jobs',
    department: 'Institute of Banking Personnel Selection',
    organization: 'IBPS Mumbai',
    state: 'All India',
    status: 'published',
    startDate: '2026-08-01',
    lastDate: '2026-08-28',
    examDate: '2026-10-19',
    resultDate: '2026-11-20',
    totalVacancy: '4,455 Vacancies',
    cutOffInfo: 'General: 54.25 | OBC: 54.25 | EWS: 54.00 | SC: 49.50 | ST: 43.00 (Out of 100 Marks in Prelims)',
    meritListInfo: 'Qualified candidates are eligible to appear for the IBPS PO Main Examination scheduled in December.',
    importantLinks: [
      { id: 'l1', name: 'Check IBPS PO Prelims Result', btnText: 'CLICK HERE', url: 'https://www.ibps.in', type: 'result', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 680 },
      { id: 'l2', name: 'Download Score Card & Marks', btnText: 'CLICK HERE', url: 'https://www.ibps.in', type: 'result', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 430 },
      { id: 'l3', name: 'Download Mains Exam Admit Card', btnText: 'CLICK HERE', url: 'https://www.ibps.in', type: 'admit_card', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 310 },
      { id: 'l4', name: 'IBPS Official Website', btnText: 'CLICK HERE', url: 'https://www.ibps.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 140 },
    ],
    officialSource: {
      websiteName: 'Institute of Banking Personnel Selection',
      websiteUrl: 'https://www.ibps.in',
      disclaimer: 'Score cards can be accessed with Registration Number / Roll Number and Password / DOB on ibps.in'
    },
    views: 5420,
    createdAt: '2026-08-20T11:00:00.000Z',
    updatedAt: '2026-08-23T09:00:00.000Z'
  },
  {
    id: 'post-6',
    slug: 'ctet-answer-key-2026-paper-1-2',
    type: 'answer_key',
    title: 'CTET Official Answer Key 2026 (Paper 1 & Paper 2) & Question Paper Challenge Link',
    shortDescription: 'Central Board of Secondary Education (CBSE) has uploaded the Official Answer Key and OMR Scanned Sheets for Central Teacher Eligibility Test (CTET) for both Primary (Paper 1) and Upper Primary (Paper 2).',
    category: 'Teaching Jobs',
    department: 'Central Board of Secondary Education (CBSE)',
    organization: 'Ministry of Education',
    state: 'All India',
    status: 'published',
    startDate: '2026-07-15',
    lastDate: '2026-08-20',
    examDate: '2026-08-10',
    answerKeyDate: '2026-08-22',
    objectionStartDate: '2026-08-22',
    objectionLastDate: '2026-08-27',
    objectionFee: '₹1,000/- per challenged question (Refundable if challenge is accepted by subject experts)',
    importantLinks: [
      { id: 'l1', name: 'Download CTET Answer Key (Paper 1 & 2)', btnText: 'CLICK HERE', url: 'https://ctet.nic.in', type: 'answer_key', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 490 },
      { id: 'l2', name: 'Submit Online Answer Key Challenge', btnText: 'CLICK HERE', url: 'https://ctet.nic.in', type: 'answer_key', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 310 },
      { id: 'l3', name: 'Download OMR Sheet & Response Sheet', btnText: 'CLICK HERE', url: 'https://ctet.nic.in', type: 'status', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 220 },
      { id: 'l4', name: 'CTET Official Website', btnText: 'CLICK HERE', url: 'https://ctet.nic.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 110 },
    ],
    officialSource: {
      websiteName: 'Central Teacher Eligibility Test (CTET)',
      websiteUrl: 'https://ctet.nic.in',
      disclaimer: 'Official keys hosted at ctet.nic.in'
    },
    views: 3820,
    createdAt: '2026-08-22T08:00:00.000Z',
    updatedAt: '2026-08-23T06:00:00.000Z'
  },
  {
    id: 'post-7',
    slug: 'pm-kisan-samman-nidhi-2026',
    type: 'sarkari_yojana',
    title: 'PM Kisan Samman Nidhi Yojana 2026: 19th Installment Check Status, e-KYC & New Farmer Registration',
    shortDescription: 'Under Pradhan Mantri Kisan Samman Nidhi (PM-KISAN), eligible landholding farmer families receive an income support of ₹6,000 per year in three equal 4-monthly installments of ₹2,000 directly into Aadhaar-seeded bank accounts.',
    category: 'PM Schemes',
    department: 'Ministry of Agriculture and Farmers Welfare',
    organization: 'Government of India',
    state: 'All India',
    status: 'published',
    isFeatured: true,
    benefits: [
      'Financial benefit of ₹6,000 per year directly transferred to bank account (DBT).',
      'Paid in 3 installments of ₹2,000 every 4 months (April-July, August-November, December-March).',
      '100% funding by the Central Government of India without intermediaries.',
      'Special Kisan Credit Card (KCC) loan facility at 4% subsidized interest rate.'
    ],
    eligibilityCriteria: [
      'All small and marginal landholding farmer families who own cultivable land.',
      'Must have Aadhaar card linked with Bank Account and active mobile number.',
      'Land revenue records (Khatauni / Khasra) verified in state portal.',
      'Institutional landholders, income tax payers, and government employees are excluded.'
    ],
    whoCanApply: 'Small and marginal farmer families with cultivable landholding in their name as per land records.',
    howToApplySteps: [
      'Visit the official PM-KISAN portal (pmkisan.gov.in) or visit Shahnawaz Computer Center.',
      'Click on "New Farmer Registration" under Farmers Corner.',
      'Select Rural Farmer Registration or Urban Farmer Registration and enter Aadhaar Number & Mobile.',
      'Verify Aadhaar OTP, choose State, District, Sub-District, Block and Village.',
      'Enter Land record Khata number, Khasra number, Area (in Hectares) and upload land deed.',
      'Submit form and complete facial or OTP e-KYC.'
    ],
    requiredDocuments: [
      'Aadhaar Card (Mandatory)',
      'Bank Account Passbook (Aadhaar Seeded / DBT Enabled)',
      'Land Ownership Documents (Khatauni / Khasra / Land Registry)',
      'Active Mobile Number for OTP verification'
    ],
    importantLinks: [
      { id: 'l1', name: 'Check Beneficiary Status Online', btnText: 'CLICK HERE', url: 'https://pmkisan.gov.in', type: 'status', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 890 },
      { id: 'l2', name: 'Complete PM Kisan e-KYC (Aadhaar OTP)', btnText: 'CLICK HERE', url: 'https://pmkisan.gov.in', type: 'apply', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 650 },
      { id: 'l3', name: 'New Farmer Online Registration', btnText: 'CLICK HERE', url: 'https://pmkisan.gov.in', type: 'apply', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 420 },
      { id: 'l4', name: 'PM-KISAN Official Website', btnText: 'CLICK HERE', url: 'https://pmkisan.gov.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 230 },
    ],
    officialSource: {
      websiteName: 'Pradhan Mantri Kisan Samman Nidhi Portal',
      websiteUrl: 'https://pmkisan.gov.in',
      disclaimer: 'Official guidelines and status are maintained on pmkisan.gov.in'
    },
    views: 7850,
    createdAt: '2026-01-10T09:00:00.000Z',
    updatedAt: '2026-08-21T15:30:00.000Z'
  },
  {
    id: 'post-8',
    slug: 'up-scholarship-online-form-2026',
    type: 'scholarship',
    title: 'UP Scholarship 2026-27: Pre-Matric & Post-Matric Online Registration, Status & Renewal Form',
    shortDescription: 'Social Welfare Department, Backward Class Welfare Department, and Minority Welfare Department of Uttar Pradesh invite online scholarship applications for 9th, 10th, 11th, 12th, UG, PG, Diploma, ITI and Professional Courses.',
    category: 'State Scholarship',
    department: 'Social Welfare Department, Government of Uttar Pradesh',
    organization: 'Government of Uttar Pradesh',
    state: 'Uttar Pradesh',
    status: 'published',
    startDate: '2026-07-01',
    lastDate: '2026-11-30',
    benefits: [
      '100% tuition fee reimbursement for eligible students.',
      'Monthly maintenance allowance directly credited to Aadhaar-seeded bank account.',
      'Financial support covering Pre-Matric (Classes 9-10) and Post-Matric (Class 11 to PhD/B.Tech/MBBS).'
    ],
    eligibilityCriteria: [
      'Domicile of Uttar Pradesh.',
      'Annual family income should not exceed ₹2,000,000 for General/OBC/Minority (₹2,50,000 for SC/ST).',
      'Enrolled in recognized schools, colleges, ITIs, Polytechnics or Universities in UP.',
      'Passed previous class without repeat.'
    ],
    requiredDocuments: [
      'Passport size photograph',
      'Income Certificate (Aay Praman Patra)',
      'Caste Certificate (Jati Praman Patra - for OBC/SC/ST)',
      'Domicile Certificate (Niwas Praman Patra)',
      'Previous Class Marksheet',
      'Current Year Fee Receipt and College ID',
      'Bank Passbook with linked NPCI DBT',
      'Aadhaar Card'
    ],
    importantLinks: [
      { id: 'l1', name: 'Fresh / Renewal Registration', btnText: 'CLICK HERE', url: 'https://scholarship.up.gov.in', type: 'apply', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 540 },
      { id: 'l2', name: 'Student Login (Pre-Matric & Post-Matric)', btnText: 'CLICK HERE', url: 'https://scholarship.up.gov.in', type: 'apply', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 390 },
      { id: 'l3', name: 'Check Scholarship Status Online', btnText: 'CLICK HERE', url: 'https://scholarship.up.gov.in', type: 'status', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 460 },
      { id: 'l4', name: 'UP Scholarship Official Portal', btnText: 'CLICK HERE', url: 'https://scholarship.up.gov.in', type: 'official', displayOrder: 4, enabled: true, openInNewTab: true, clickCount: 160 },
    ],
    officialSource: {
      websiteName: 'Uttar Pradesh Scholarship & Fee Reimbursement Online System',
      websiteUrl: 'https://scholarship.up.gov.in',
      disclaimer: 'Official scholarship portal is scholarship.up.gov.in'
    },
    views: 4630,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-08-19T17:00:00.000Z'
  },
  {
    id: 'post-9',
    slug: 'neet-ug-2026-counselling-admission',
    type: 'admission',
    title: 'NEET UG 2026 All India Quota (AIQ) & State MBBS / BDS Counselling & Admission Online Form',
    shortDescription: 'Medical Counselling Committee (MCC) and State Medical Admission Authorities have commenced Online Registration, Choice Filling and Seat Allotment for 15% AIQ and 85% State Quota MBBS/BDS/BAMS/BHMS/B.Sc Nursing Seats.',
    category: 'Entrance Exam',
    department: 'Medical Counselling Committee (MCC) / DGHS',
    organization: 'Ministry of Health and Family Welfare',
    state: 'All India',
    status: 'published',
    startDate: '2026-08-10',
    lastDate: '2026-09-15',
    feeStructure: {
      general: '₹1,000 (Non-refundable) + ₹10,000 (Refundable Security)',
      obc: '₹500 (Non-refundable) + ₹10,000 (Refundable Security)',
      ews: '₹500 (Non-refundable) + ₹10,000 (Refundable Security)',
      sc: '₹500 (Non-refundable) + ₹5,000 (Refundable Security)',
      st: '₹500 (Non-refundable) + ₹5,000 (Refundable Security)',
      female: 'As per Category',
      phOrOther: '₹500 (Non-refundable) + ₹5,000 (Refundable Security)',
      paymentMode: 'Net Banking / Credit / Debit Card'
    },
    requiredDocuments: [
      'NEET UG 2026 Admit Card and Score Card / Rank Letter',
      'Class 10th & 12th Certificate and Marksheet',
      'Eight Passport Size Photographs (same as on application)',
      'Provisional Allotment Letter generated online',
      'Proof of Identity (Aadhaar / PAN / Driving License / Passport)',
      'Category Certificate (SC/ST/OBC-NCL/EWS/PwD) if applicable'
    ],
    importantLinks: [
      { id: 'l1', name: 'MCC AIQ Counselling Registration & Choice Filling', btnText: 'CLICK HERE', url: 'https://mcc.nic.in', type: 'apply', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 310 },
      { id: 'l2', name: 'Download Seat Matrix & Information Bulletin', btnText: 'CLICK HERE', url: 'https://mcc.nic.in', type: 'notification', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 195 },
      { id: 'l3', name: 'MCC Official Website', btnText: 'CLICK HERE', url: 'https://mcc.nic.in', type: 'official', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 95 },
    ],
    officialSource: {
      websiteName: 'Medical Counselling Committee (MCC)',
      websiteUrl: 'https://mcc.nic.in',
      disclaimer: 'Official seat allocation conducted via mcc.nic.in'
    },
    views: 2980,
    createdAt: '2026-08-10T11:00:00.000Z',
    updatedAt: '2026-08-21T10:00:00.000Z'
  },
  {
    id: 'post-10',
    slug: 'ssc-gd-constable-syllabus-exam-pattern-2026',
    type: 'syllabus',
    title: 'SSC GD Constable 2026 Complete Syllabus PDF, Exam Pattern & Physical Test (PET/PST) Standards',
    shortDescription: 'Check Staff Selection Commission (SSC) Constable (GD) in Central Armed Police Forces (CAPFs), SSF, and Rifleman (GD) in Assam Rifles Examination 2026 topic-wise syllabus, marks distribution and physical standards.',
    category: 'SSC Jobs',
    department: 'Staff Selection Commission (SSC)',
    organization: 'Ministry of Home Affairs',
    state: 'All India',
    status: 'published',
    examPattern: 'Computer Based Examination (CBE) contains 80 objective questions (160 marks). Each section has 20 questions (40 marks): (A) General Intelligence and Reasoning, (B) General Knowledge and General Awareness, (C) Elementary Mathematics, (D) English/Hindi. Duration: 60 minutes. Negative Marking: 0.25 marks for each incorrect answer.',
    syllabus: 'Reasoning: Analogies, Similarities, Spatial Orientation, Visual Memory, Coding-Decoding. General Knowledge: Indian History, Culture, Geography, Economic Scene, General Policy, Indian Constitution, Scientific Research. Mathematics: Number Systems, Decimals, Fractions, Ratio & Proportion, Averages, Interest, Profit & Loss, Discount, Mensuration, Time & Distance, Time & Work.',
    importantLinks: [
      { id: 'l1', name: 'Download SSC GD Syllabus PDF', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'syllabus', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 380 },
      { id: 'l2', name: 'Download Previous 5 Years Question Papers', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'syllabus', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 290 },
      { id: 'l3', name: 'Official SSC Portal', btnText: 'CLICK HERE', url: 'https://ssc.gov.in', type: 'official', displayOrder: 3, enabled: true, openInNewTab: true, clickCount: 110 },
    ],
    officialSource: {
      websiteName: 'Staff Selection Commission',
      websiteUrl: 'https://ssc.gov.in',
      disclaimer: 'Official syllabus is detailed in SSC GD examination notification at ssc.gov.in'
    },
    views: 2450,
    createdAt: '2026-05-10T12:00:00.000Z',
    updatedAt: '2026-08-15T09:00:00.000Z'
  },
  {
    id: 'post-11',
    slug: 'nta-jee-main-2027-session-1-exam-date-notice',
    type: 'notice',
    title: 'NTA JEE Main 2027 Session 1 & 2 Examination Calendar & Important Information Notice',
    shortDescription: 'National Testing Agency (NTA) has released the Public Notice regarding the examination schedule for Joint Entrance Examination (Main) 2027 for admission to B.E./B.Tech, B.Arch and B.Planning courses in NITs, IIITs and CFTIs.',
    category: 'Entrance Exam',
    department: 'National Testing Agency (NTA)',
    organization: 'Ministry of Education',
    state: 'All India',
    status: 'published',
    startDate: '2026-11-01',
    lastDate: '2026-12-04',
    examDate: '2027-01-22 to 2027-01-31',
    importantLinks: [
      { id: 'l1', name: 'Download NTA Public Notice PDF', btnText: 'CLICK HERE', url: 'https://jeemain.nta.ac.in', type: 'notification', displayOrder: 1, enabled: true, openInNewTab: true, clickCount: 210 },
      { id: 'l2', name: 'JEE Main Official Website', btnText: 'CLICK HERE', url: 'https://jeemain.nta.ac.in', type: 'official', displayOrder: 2, enabled: true, openInNewTab: true, clickCount: 130 },
    ],
    officialSource: {
      websiteName: 'National Testing Agency (NTA JEE Main)',
      websiteUrl: 'https://jeemain.nta.ac.in',
      disclaimer: 'Official notices published on nta.ac.in and jeemain.nta.ac.in'
    },
    views: 1890,
    createdAt: '2026-08-15T08:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z'
  }
];

export const INITIAL_SETTINGS: SiteSettings = {
  websiteName: 'SHAHNAWAZ COMPUTER CENTER',
  tagline: 'Latest Jobs, Results, Admit Card, Sarkari Yojana & Online Form Updates',
  description: 'Mobile-first Government Jobs, Results, Admit Card, Answer Key, Sarkari Yojana, Scholarship, Admission and Online Information Portal.',
  logoText: 'SHAHNAWAZ COMPUTER CENTER',
  whatsAppUrl: 'https://whatsapp.com/channel/0029VbDh3ZP3QxRsUixBEU1P',
  whatsAppNumber: '+91 99560 78419',
  telegramUrl: 'https://t.me/ShahnawazComputerCenter',
  contactNumber: '+91 99560 78419',
  contactEmail: 'mohdshahnawaz.afaque@gmail.com',
  address: 'Shahnawaz Computer Center, Tambour, District Sitapur, Uttar Pradesh, India',
  timing: 'Monday - Saturday: 8:00 AM to 8:30 PM | Sunday: 9:00 AM to 2:00 PM',
  footerText: 'Shahnawaz Computer Center is an independent digital information and online services portal. We provide verified updates regarding Government recruitment, Sarkari Result, Admit Cards, Sarkari Yojana and education notices.',
  metaDescription: 'Get Latest Government Jobs, Sarkari Results, Admit Cards, Answer Keys, Syllabus, Sarkari Yojana, UP Scholarship & Online Form updates at Shahnawaz Computer Center.',
  keywords: 'Sarkari Naukri, Sarkari Result, Admit Card 2026, Government Jobs 2026, UP Police, SSC CGL, RRB NTPC, PM Kisan, UP Scholarship, Shahnawaz Computer Center',
  homeSectionsOrder: [
    'announcements',
    'quickBadges',
    'socialBanner',
    'featuredJobs',
    'admitCards',
    'results',
    'answerKeys',
    'sarkariYojana',
    'admissions',
    'scholarships',
    'syllabus',
    'notices',
    'services',
  ],
  enabledSections: {
    announcements: true,
    quickBadges: true,
    socialBanner: true,
    featuredJobs: true,
    admitCards: true,
    results: true,
    answerKeys: true,
    sarkariYojana: true,
    admissions: true,
    scholarships: true,
    syllabus: true,
    notices: true,
    services: true,
    ads: true,
  }
};

export const INITIAL_ADS: Advertisement[] = [
  {
    id: 'ad-1',
    placement: 'header',
    title: 'Header Notice Banner',
    codeHtml: '',
    imageUrl: '',
    targetUrl: '',
    enabled: false,
  },
  {
    id: 'ad-2',
    placement: 'home_middle',
    title: 'Computer Center Fast Service Banner',
    codeHtml: '',
    imageUrl: '',
    targetUrl: '',
    enabled: true,
  },
  {
    id: 'ad-3',
    placement: 'post_before_links',
    title: 'Post Detail Before Important Links',
    codeHtml: '',
    imageUrl: '',
    targetUrl: '',
    enabled: true,
  },
  {
    id: 'ad-4',
    placement: 'post_after_links',
    title: 'Post Detail After Important Links',
    codeHtml: '',
    imageUrl: '',
    targetUrl: '',
    enabled: true,
  },
  {
    id: 'ad-5',
    placement: 'sidebar',
    title: 'Sidebar Advertisement',
    codeHtml: '',
    imageUrl: '',
    targetUrl: '',
    enabled: true,
  }
];

export const INITIAL_COMMENTS: PostComment[] = [
  {
    id: 'cmt-1',
    postId: 'post-1',
    postSlug: 'ssc-cgl-recruitment-2026',
    authorName: 'Shahnawaz Computer Center (Helpdesk)',
    authorBadge: 'Staff • Verified Admin',
    authorLocation: 'Tambour, Sitapur',
    tag: 'update',
    content: '📌 Important Notice for SSC CGL 2026 Applicants: Live photo capture is mandatory through the SSC Official App. Please ensure clear lighting and plain light background. If you face camera alignment or OTP issues, visit our center for assisted form filling.',
    createdAt: '2026-08-20T10:30:00.000Z',
    likes: 28,
    isPinned: true,
    isStaff: true,
    replies: [
      {
        id: 'rep-1',
        authorName: 'Vikas Mishra',
        authorBadge: 'Aspirant • Sitapur',
        authorLocation: 'Sitapur',
        isStaff: false,
        content: 'Thank you bhaiya! Center timing kya hai form bharwane ke liye?',
        createdAt: '2026-08-20T11:15:00.000Z',
        likes: 5,
      },
      {
        id: 'rep-2',
        authorName: 'Shahnawaz Computer Center',
        authorBadge: 'Staff',
        authorLocation: 'Tambour',
        isStaff: true,
        content: 'Our center is open daily from 8:00 AM to 8:00 PM. You can also send documents directly on WhatsApp for online submission.',
        createdAt: '2026-08-20T11:20:00.000Z',
        likes: 9,
      }
    ]
  },
  {
    id: 'cmt-2',
    postId: 'post-1',
    postSlug: 'ssc-cgl-recruitment-2026',
    authorName: 'Anjali Sharma',
    authorBadge: 'Graduate Aspirant',
    authorLocation: 'Lucknow',
    tag: 'question',
    content: 'Is final year appearing candidate eligible to apply for Assistant Section Officer (ASO) in CSS this year?',
    createdAt: '2026-08-21T09:12:00.000Z',
    likes: 14,
    isPinned: false,
    isStaff: false,
    replies: [
      {
        id: 'rep-3',
        authorName: 'Rohan Gupta',
        authorBadge: 'SSC Aspirant',
        authorLocation: 'Prayagraj',
        isStaff: false,
        content: 'Yes Anjali, as per notification, you must acquire the essential qualification on or before the crucial cutoff date (01-08-2026).',
        createdAt: '2026-08-21T10:05:00.000Z',
        likes: 12,
      }
    ]
  },
  {
    id: 'cmt-3',
    postId: 'post-1',
    postSlug: 'ssc-cgl-recruitment-2026',
    authorName: 'Deepak Yadav',
    authorBadge: 'OBC Candidate',
    authorLocation: 'Kanpur',
    tag: 'tip',
    content: '💡 Preparation Tip: Focus heavily on Reasoning & Math speed with sectional mock tests. Don’t skip Computer Knowledge & Typing test preparation, as qualifying marks in Tier-II computer paper are mandatory for all ministerial posts.',
    createdAt: '2026-08-22T14:40:00.000Z',
    likes: 31,
    isPinned: false,
    isStaff: false,
    replies: []
  },
  {
    id: 'cmt-4',
    postId: 'post-2',
    postSlug: 'up-police-constable-admit-card-2026',
    authorName: 'Shahnawaz Computer Center',
    authorBadge: 'Staff • Verified Admin',
    authorLocation: 'Tambour, Sitapur',
    tag: 'update',
    content: '📢 Candidates please print at least 2 clean color copies of the Admit Card along with the self-declaration undertaking. Carry Original Aadhaar Card and 2 recent passport size photographs to the examination center.',
    createdAt: '2026-08-23T08:00:00.000Z',
    likes: 45,
    isPinned: true,
    isStaff: true,
    replies: []
  },
  {
    id: 'cmt-5',
    postId: 'post-2',
    postSlug: 'up-police-constable-admit-card-2026',
    authorName: 'Mohit Kumar',
    authorBadge: 'Aspirant',
    authorLocation: 'Lakhimpur',
    tag: 'question',
    content: 'My admit card has a slight spelling mistake in mother’s name. What should I do for the exam hall entry?',
    createdAt: '2026-08-23T12:30:00.000Z',
    likes: 8,
    isPinned: false,
    isStaff: false,
    replies: [
      {
        id: 'rep-4',
        authorName: 'Shahnawaz Computer Center',
        authorBadge: 'Staff',
        authorLocation: 'Tambour',
        isStaff: true,
        content: 'Carry your 10th marksheet original along with an Affidavit / valid ID card with correct details. Also contact board helpline or reach center 1 hour early for verification.',
        createdAt: '2026-08-23T12:45:00.000Z',
        likes: 16,
      }
    ]
  }
];
export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Welcome to Shahnawaz Computer Center',
    description: 'Get all your online forms, results, and computer services done with high quality.',
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=1200',
    contactNumber: '919876543210',
    whatsAppNumber: '919876543210',
    promotionalLink: '/services',
    isActive: true,
    order: 1
  }
];
