export interface BulkGovRecord {
  title: string;
  organization: string;
  category: 'Vacancy' | 'Admit Card' | 'Result' | string;
  state: string;
  publishDate?: string;
  lastDate?: string;
  examDate?: string;
  officialNotificationUrl?: string;
  officialApplyUrl?: string;
  officialAdmitCardUrl?: string;
  officialResultUrl?: string;
  sourceUrl?: string;
  status: 'Active' | 'Closed' | 'Released' | 'Old' | string;
  totalVacancy?: string;
  educationalQualification?: string;
  shortDescription?: string;
}

export const VERIFIED_GOVERNMENT_DATABASE: BulkGovRecord[] = [
  // =========================================================================
  // 1. VACANCIES / RECRUITMENTS (JOBS)
  // =========================================================================
  {
    title: 'SSC CGL 2026 Combined Graduate Level Examination',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-06-15',
    lastDate: '2026-07-24',
    examDate: '2026-09-15 to 2026-09-28',
    totalVacancy: '14,582 Posts',
    educationalQualification: 'Bachelor’s Degree in any discipline from a recognized University in India.',
    shortDescription: 'SSC invites online applications for recruitment to Group B and Group C posts in various Ministries, Departments, and Organizations of the Government of India.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Active'
  },
  {
    title: 'SSC CHSL 10+2 Combined Higher Secondary Level Recruitment 2026',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-04-08',
    lastDate: '2026-05-07',
    examDate: '2026-07-01 to 2026-07-12',
    totalVacancy: '3,712 Posts',
    educationalQualification: '12th Standard or equivalent examination from a recognized Board or University.',
    shortDescription: 'Recruitment for Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), and Data Entry Operator (DEO) across Central Government offices.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Active'
  },
  {
    title: 'SSC GD Constable in CAPFs, SSF, Rifleman in Assam Rifles 2026',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-08-10',
    lastDate: '2026-09-15',
    examDate: '2026-11-15 to 2026-12-05',
    totalVacancy: '39,481 Posts',
    educationalQualification: '10th Class (Matriculation) Pass from a recognized Board in India.',
    shortDescription: 'Direct recruitment of Constables (General Duty) in BSF, CISF, CRPF, SSB, ITBP, AR and SSF forces.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Active'
  },
  {
    title: 'SSC MTS & Havaldar (CBIC & CBN) Recruitment Examination 2026',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-05-20',
    lastDate: '2026-06-25',
    examDate: '2026-08-18 to 2026-09-02',
    totalVacancy: '9,583 Posts',
    educationalQualification: 'Matriculation (10th Pass) from a recognized Board.',
    shortDescription: 'Multi Tasking (Non-Technical) Staff and Havaldar in Central Board of Indirect Taxes and Narcotics Department.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Active'
  },
  {
    title: 'SSC CPO Sub-Inspector in Delhi Police & Central Armed Police Forces',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-03-04',
    lastDate: '2026-04-02',
    examDate: '2026-06-27 to 2026-06-29',
    totalVacancy: '4,187 Posts',
    educationalQualification: 'Graduation in any stream with valid Driving License for Delhi Police.',
    shortDescription: 'Recruitment of Sub-Inspectors (Executive) in Delhi Police and Sub-Inspectors (GD) in BSF, CISF, CRPF, ITBP, SSB.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialApplyUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Closed'
  },
  {
    title: 'UPSC Civil Services Examination (IAS / IPS / IFS) 2026',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-02-14',
    lastDate: '2026-03-05',
    examDate: '2026-05-25',
    totalVacancy: '1,056 Posts',
    educationalQualification: 'Degree from any recognized Central, State or Deemed University.',
    shortDescription: 'Preliminary examination for recruitment to Indian Administrative Service, Indian Foreign Service, Indian Police Service and Group A/B Central Services.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialApplyUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Active'
  },
  {
    title: 'UPSC National Defence Academy & Naval Academy Examination (NDA-II) 2026',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-05-15',
    lastDate: '2026-06-04',
    examDate: '2026-09-01',
    totalVacancy: '404 Posts',
    educationalQualification: '12th Class Pass of the 10+2 pattern (with Physics, Chemistry, Maths for Air Force/Navy).',
    shortDescription: 'Admission to the Army, Navy and Air Force wings of the NDA for the 154th Course and 116th Indian Naval Academy Course (INAC).',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialApplyUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Active'
  },
  {
    title: 'UPSC Combined Defence Services Examination (CDS-II) 2026',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-05-15',
    lastDate: '2026-06-04',
    examDate: '2026-09-01',
    totalVacancy: '459 Posts',
    educationalQualification: 'Degree for IMA/OTA, Engineering for Air Force Academy, B.Sc/Engg for Naval Academy.',
    shortDescription: 'Direct officer entry in Indian Military Academy Dehradun, Indian Naval Academy Ezhimala, Air Force Academy Hyderabad, and OTA Chennai.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialApplyUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Active'
  },
  {
    title: 'RRB NTPC Non-Technical Popular Categories (Graduate & Undergraduate)',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-08-01',
    lastDate: '2026-09-15',
    examDate: '2026-11-20',
    totalVacancy: '11,558 Posts',
    educationalQualification: '12th Pass for Undergraduate Level Posts and Graduate Degree for Graduate Level Posts.',
    shortDescription: 'Recruitment of Station Master, Goods Train Manager, Commercial cum Ticket Clerk, Junior Clerk cum Typist across all Indian Railway zones.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialApplyUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Active'
  },
  {
    title: 'RRB ALP Assistant Loco Pilot Direct Recruitment 2026',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-01-20',
    lastDate: '2026-02-19',
    examDate: '2026-08-28 to 2026-09-06',
    totalVacancy: '18,799 Posts',
    educationalQualification: 'Matriculation / 10th plus ITI in specified trades, or Diploma / Degree in Mechanical / Electrical / Electronics / Automobile Engineering.',
    shortDescription: 'Centrally revised recruitment of Assistant Loco Pilots in Zonal Railways with countrywide CBT examination.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialApplyUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Active'
  },
  {
    title: 'RRB Technician Grade-I Signal & Grade-III Various Trades 2026',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-03-09',
    lastDate: '2026-04-08',
    examDate: '2026-10-15',
    totalVacancy: '14,298 Posts',
    educationalQualification: 'B.Sc / Diploma / Degree in Engineering for Grade I Signal, and 10th + ITI for Grade III Technician.',
    shortDescription: 'Recruitment of Technicians in Indian Railway workshops, electrical, mechanical, civil and signal departments.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialApplyUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Active'
  },
  {
    title: 'IBPS PO / Management Trainee CRP PO/MT-XIV Recruitment 2026',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-08-01',
    lastDate: '2026-08-28',
    examDate: '2026-10-19 to 2026-10-20',
    totalVacancy: '4,455 Posts',
    educationalQualification: 'A Degree (Graduation) in any discipline from a recognized University by Govt of India.',
    shortDescription: 'Common Recruitment Process for selection of Probationary Officers in 11 Participating Public Sector Banks across India.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialApplyUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Active'
  },
  {
    title: 'IBPS Clerk CRP Clerical Cadre-XIV Recruitment 2026',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-07-01',
    lastDate: '2026-07-28',
    examDate: '2026-08-24 to 2026-08-31',
    totalVacancy: '6,128 Posts',
    educationalQualification: 'Graduation in any discipline and proficiency in the official language of the concerned State/UT.',
    shortDescription: 'Customer Service Associates / Clerks recruitment in Nationalized Public Sector Banks.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialApplyUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Active'
  },
  {
    title: 'IBPS RRB Officer Scale-I, II, III & Office Assistant (Multipurpose) CRP-XIII',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-06-07',
    lastDate: '2026-06-30',
    examDate: '2026-08-03 to 2026-08-18',
    totalVacancy: '9,923 Posts',
    educationalQualification: 'Bachelor’s Degree in any discipline with local regional language knowledge.',
    shortDescription: 'Recruitment in 43 Regional Rural Banks (Gramin Banks) across all Indian States and Union Territories.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialApplyUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Active'
  },
  {
    title: 'SBI Probationary Officer (PO) Direct Recruitment 2026',
    organization: 'State Bank of India (SBI)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-09-01',
    lastDate: '2026-09-27',
    examDate: '2026-11-01',
    totalVacancy: '2,000 Posts',
    educationalQualification: 'Graduation in any discipline from a recognized University.',
    shortDescription: 'State Bank of India invites online applications for appointment as Probationary Officers across all branches in India.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialApplyUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Active'
  },
  {
    title: 'SBI Junior Associate (Customer Support & Sales / Clerk) 2026',
    organization: 'State Bank of India (SBI)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-01-10',
    lastDate: '2026-02-05',
    examDate: '2026-04-10',
    totalVacancy: '8,283 Posts',
    educationalQualification: 'Graduation in any discipline with state local language fluency.',
    shortDescription: 'Recruitment of Junior Associates in clerical cadre in State Bank of India.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialApplyUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Closed'
  },
  {
    title: 'UP Police Constable Civil Police Direct Recruitment 2026 (60,244 Posts)',
    organization: 'UP Police Recruitment and Promotion Board (UPPRPB)',
    category: 'Vacancy',
    state: 'Uttar Pradesh',
    publishDate: '2026-01-15',
    lastDate: '2026-02-28',
    examDate: '2026-08-23 to 2026-08-31',
    totalVacancy: '60,244 Posts',
    educationalQualification: 'Intermediate (10+2) Pass from recognized Board or equivalent.',
    shortDescription: 'Direct recruitment for Constable Civil Police in Uttar Pradesh Police Force under UPPRPB Lucknow.',
    officialNotificationUrl: 'https://uppbpb.gov.in',
    officialApplyUrl: 'https://uppbpb.gov.in',
    sourceUrl: 'https://uppbpb.gov.in',
    status: 'Active'
  },
  {
    title: 'UP Police Sub Inspector (SI) & Confidential / Assistant Sub Inspector',
    organization: 'UP Police Recruitment and Promotion Board (UPPRPB)',
    category: 'Vacancy',
    state: 'Uttar Pradesh',
    publishDate: '2026-03-01',
    lastDate: '2026-04-15',
    examDate: '2026-09-20',
    totalVacancy: '921 Posts',
    educationalQualification: "Graduation Degree + 'O' Level Computer Certificate / PGDCA with Hindi/English Typing.",
    shortDescription: 'Recruitment for Sub-Inspector (Confidential), ASI (Clerk) and ASI (Accounts) in UP Police.',
    officialNotificationUrl: 'https://uppbpb.gov.in',
    officialApplyUrl: 'https://uppbpb.gov.in',
    sourceUrl: 'https://uppbpb.gov.in',
    status: 'Active'
  },
  {
    title: 'UPPSC Combined State / Upper Subordinate Services (PCS) Examination 2026',
    organization: 'Uttar Pradesh Public Service Commission (UPPSC)',
    category: 'Vacancy',
    state: 'Uttar Pradesh',
    publishDate: '2026-01-01',
    lastDate: '2026-02-02',
    examDate: '2026-10-27',
    totalVacancy: '220 Posts',
    educationalQualification: 'Bachelor’s Degree in any stream from recognized Indian University.',
    shortDescription: 'State civil services recruitment for SDM, DSP, BDO, ARTO, DPRO and other administrative officers in Uttar Pradesh.',
    officialNotificationUrl: 'https://uppsc.up.nic.in',
    officialApplyUrl: 'https://uppsc.up.nic.in',
    sourceUrl: 'https://uppsc.up.nic.in',
    status: 'Active'
  },
  {
    title: 'UPSSSC Preliminary Eligibility Test (PET) 2026',
    organization: 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)',
    category: 'Vacancy',
    state: 'Uttar Pradesh',
    publishDate: '2026-06-01',
    lastDate: '2026-07-10',
    examDate: '2026-10-28 to 2026-10-29',
    totalVacancy: 'Mandatory Qualifying Exam',
    educationalQualification: 'High School (10th) or higher educational qualification.',
    shortDescription: 'Mandatory gateway examination for all Group C Government Jobs in Uttar Pradesh including Lekhpal, VDO, Junior Assistant.',
    officialNotificationUrl: 'https://upsssc.gov.in',
    officialApplyUrl: 'https://upsssc.gov.in',
    sourceUrl: 'https://upsssc.gov.in',
    status: 'Active'
  },
  {
    title: 'BPSC 70th Integrated Combined Competitive Examination (CCE) 2026',
    organization: 'Bihar Public Service Commission (BPSC)',
    category: 'Vacancy',
    state: 'Bihar',
    publishDate: '2026-07-15',
    lastDate: '2026-08-25',
    examDate: '2026-11-17',
    totalVacancy: '1,957 Posts',
    educationalQualification: 'Graduation Degree in any stream from a recognized University.',
    shortDescription: 'Bihar administrative, police, revenue, and municipal service officer recruitment examination.',
    officialNotificationUrl: 'https://bpsc.bih.nic.in',
    officialApplyUrl: 'https://bpsc.bih.nic.in',
    sourceUrl: 'https://bpsc.bih.nic.in',
    status: 'Active'
  },
  {
    title: 'Bihar Police Constable Direct Recruitment (21,391 Posts)',
    organization: 'Central Selection Board of Constable (CSBC) Bihar',
    category: 'Vacancy',
    state: 'Bihar',
    publishDate: '2026-06-20',
    lastDate: '2026-07-20',
    examDate: '2026-08-07 to 2026-08-28',
    totalVacancy: '21,391 Posts',
    educationalQualification: '10+2 (Intermediate) Pass from a recognized Board in India.',
    shortDescription: 'Direct recruitment of Constables in Bihar Police and Special Armed Police units.',
    officialNotificationUrl: 'https://csbc.bih.nic.in',
    officialApplyUrl: 'https://csbc.bih.nic.in',
    sourceUrl: 'https://csbc.bih.nic.in',
    status: 'Active'
  },
  {
    title: 'DSSSB Delhi Teaching (TGT / PGT / PRT) & Non-Teaching Recruitment 2026',
    organization: 'Delhi Subordinate Services Selection Board (DSSSB)',
    category: 'Vacancy',
    state: 'Delhi',
    publishDate: '2026-03-12',
    lastDate: '2026-04-18',
    examDate: '2026-08-12 to 2026-09-05',
    totalVacancy: '5,118 Posts',
    educationalQualification: 'Graduation / Post Graduation with B.Ed / D.El.Ed / CTET as applicable post-wise.',
    shortDescription: 'Recruitment for Directorate of Education, Municipal Corporation of Delhi, and NDMC schools.',
    officialNotificationUrl: 'https://dsssb.delhi.gov.in',
    officialApplyUrl: 'https://dsssbonline.nic.in',
    sourceUrl: 'https://dsssb.delhi.gov.in',
    status: 'Active'
  },
  {
    title: 'Indian Air Force Agniveervayu Intake 01/2026 Direct Recruitment',
    organization: 'Indian Air Force (IAF)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-01-17',
    lastDate: '2026-02-11',
    examDate: '2026-03-17',
    totalVacancy: '3,500+ Posts (Men & Women)',
    educationalQualification: '10+2 with Mathematics, Physics and English with min 50% marks OR 3 Yrs Diploma in Engineering.',
    shortDescription: 'Join Indian Air Force under the Agnipath Scheme as Agniveervayu for Science and Non-Science Subjects.',
    officialNotificationUrl: 'https://agnipathvayu.cdac.in',
    officialApplyUrl: 'https://agnipathvayu.cdac.in',
    sourceUrl: 'https://agnipathvayu.cdac.in',
    status: 'Active'
  },
  {
    title: 'Join Indian Army Agniveer Rally Recruitment 2026',
    organization: 'Indian Army (HQ Recruiting Zone)',
    category: 'Vacancy',
    state: 'All India',
    publishDate: '2026-02-13',
    lastDate: '2026-03-22',
    examDate: '2026-04-22 to 2026-05-03',
    totalVacancy: '25,000+ Posts (All ZRO / ARO)',
    educationalQualification: '10th / 8th / 12th Pass as per trade (GD, Technical, Clerk, Tradesman).',
    shortDescription: 'Recruitment of Agniveer General Duty, Technical, Office Assistant / Clerk, and Tradesmen in the Indian Army.',
    officialNotificationUrl: 'https://joinindianarmy.nic.in',
    officialApplyUrl: 'https://joinindianarmy.nic.in',
    sourceUrl: 'https://joinindianarmy.nic.in',
    status: 'Active'
  },

  // =========================================================================
  // 2. ADMIT CARDS / CALL LETTERS / EXAM CITY SLIPS
  // =========================================================================
  {
    title: 'UP Police Constable 2026 Re-Exam Admit Card & Exam District Slip Released',
    organization: 'UP Police Recruitment and Promotion Board (UPPRPB)',
    category: 'Admit Card',
    state: 'Uttar Pradesh',
    publishDate: '2026-08-16',
    examDate: '2026-08-23 to 2026-08-31',
    shortDescription: 'UPPRPB has activated the candidate portal to download the official E-Admit Card and check District/City Intimation slip for 60,244 Constable posts.',
    officialNotificationUrl: 'https://uppbpb.gov.in',
    officialAdmitCardUrl: 'https://uppbpb.gov.in',
    sourceUrl: 'https://uppbpb.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC CGL Tier-I 2026 Examination City Intimation & E-Admit Card',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-09-05',
    examDate: '2026-09-15 to 2026-09-28',
    shortDescription: 'Download SSC CGL Tier-1 Hall Ticket and Check Application Status / Examination Shift timings across all SSC Regional Websites.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialAdmitCardUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC CHSL 10+2 Tier-I Computer Based Test Admit Card 2026',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-06-20',
    examDate: '2026-07-01 to 2026-07-12',
    shortDescription: 'SSC CHSL Tier-I Admit Card and Exam Date Slip download link active for CR, NR, ER, WR, SR, KKR, NER, MPR, NWR regions.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialAdmitCardUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC GD Constable Physical Test (PET / PST) Call Letter 2026',
    organization: 'Staff Selection Commission (SSC) & CRPF',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-18',
    examDate: '2026-09-02 to 2026-09-20',
    shortDescription: 'Download Physical Standard Test (PST) and Physical Efficiency Test (PET) e-Admit Card for shortlisted SSC GD Constable candidates.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialAdmitCardUrl: 'https://rect.crpf.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC Civil Services (IAS) Preliminary Examination E-Admit Card 2026',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-05-10',
    examDate: '2026-05-25',
    shortDescription: 'UPSC has issued the E-Admit Card for Civil Services Preliminary Exam. Candidates must carry printout along with original photo ID proof.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialAdmitCardUrl: 'https://upsconline.nic.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC NDA & NA (II) 2026 Examination Hall Ticket Download',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-15',
    examDate: '2026-09-01',
    shortDescription: 'National Defence Academy and Naval Academy Examination (II) E-Admit Card download link activated on upsconline.nic.in.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialAdmitCardUrl: 'https://upsconline.nic.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC CDS (II) 2026 Examination E-Admit Card Available Online',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-15',
    examDate: '2026-09-01',
    shortDescription: 'Combined Defence Services Examination (II) Hall ticket released by UPSC. Verify examination center details and roll number.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialAdmitCardUrl: 'https://upsconline.nic.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'RRB ALP (Assistant Loco Pilot) CBT-1 Exam City Slip & E-Call Letter',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-17',
    examDate: '2026-08-28 to 2026-09-06',
    shortDescription: 'Indian Railways has published the exam city & travel pass for RRB ALP CEN 01/2024. E-Call Letter available 4 days before exam date.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialAdmitCardUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Released'
  },
  {
    title: 'RRB Technician CBT Exam City Intimation & Hall Ticket 2026',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-10-01',
    examDate: '2026-10-15 to 2026-10-25',
    shortDescription: 'Download CBT E-Call Letter and Free Sleeper Travel Authority for SC/ST candidates for RRB Technician Grade-I & III.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialAdmitCardUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Released'
  },
  {
    title: 'RRB NTPC CBT-1 Stage Examination Call Letter 2026',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-11-10',
    examDate: '2026-11-20',
    shortDescription: 'Railway NTPC Graduate & Undergraduate Stage 1 CBT Hall Ticket link opened across all 21 RRB regional portals.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialAdmitCardUrl: 'https://rrbcdg.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Released'
  },
  {
    title: 'IBPS PO / MT Prelims Online Examination Call Letter 2026',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-10-05',
    examDate: '2026-10-19 to 2026-10-20',
    shortDescription: 'Download Online Preliminary Examination Call Letter for Probationary Officers in participating public sector banks.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialAdmitCardUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'IBPS Clerk Prelims Online Exam Call Letter 2026',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-12',
    examDate: '2026-08-24 to 2026-08-31',
    shortDescription: 'IBPS has released the preliminary examination admit card for Clerical Cadre (CRP Clerks-XIV).',
    officialNotificationUrl: 'https://www.ibps.in',
    officialAdmitCardUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'IBPS RRB Officer Scale-I & Office Assistant Main Exam Call Letter',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-09-18',
    examDate: '2026-09-29',
    shortDescription: 'Call letter for Online Main Examination for recruitment of Officers Scale-I and Office Assistants in Regional Rural Banks.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialAdmitCardUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'SBI PO Preliminary Examination Call Letter 2026',
    organization: 'State Bank of India (SBI)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-10-20',
    examDate: '2026-11-01 to 2026-11-06',
    shortDescription: 'Download State Bank of India Probationary Officer Phase-I Prelims Admit Card with Roll Number and Center Details.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialAdmitCardUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Released'
  },
  {
    title: 'SBI Junior Associate (Clerk) Main Examination Admit Card 2026',
    organization: 'State Bank of India (SBI)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-03-28',
    examDate: '2026-04-10',
    shortDescription: 'SBI Clerk Phase-II Mains examination call letter released for candidates who qualified the Preliminary examination.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialAdmitCardUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Released'
  },
  {
    title: 'NTA UGC NET Exam City Intimation & Admit Card 2026',
    organization: 'National Testing Agency (NTA)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-08-15',
    examDate: '2026-08-21 to 2026-09-04',
    shortDescription: 'National Testing Agency (NTA) has released Subject-wise Exam City Slip and E-Admit Card for UGC NET JRF & Assistant Professor.',
    officialNotificationUrl: 'https://ugcnet.nta.ac.in',
    officialAdmitCardUrl: 'https://ugcnet.nta.ac.in',
    sourceUrl: 'https://nta.ac.in',
    status: 'Released'
  },
  {
    title: 'CTET Central Teacher Eligibility Test Admit Card & Exam Center Slip',
    organization: 'Central Board of Secondary Education (CBSE)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-07-02',
    examDate: '2026-07-07',
    shortDescription: 'CBSE has made available the online admit card for Paper-I (Class 1-5) and Paper-II (Class 6-8) CTET Examination.',
    officialNotificationUrl: 'https://ctet.nic.in',
    officialAdmitCardUrl: 'https://ctet.nic.in',
    sourceUrl: 'https://ctet.nic.in',
    status: 'Released'
  },
  {
    title: 'UPPSC Combined State / Upper Subordinate (PCS) Prelims Hall Ticket',
    organization: 'Uttar Pradesh Public Service Commission (UPPSC)',
    category: 'Admit Card',
    state: 'Uttar Pradesh',
    publishDate: '2026-10-15',
    examDate: '2026-10-27',
    shortDescription: 'Download UPPSC PCS Prelims Admit Card using Registration Number and Date of Birth on uppsc.up.nic.in.',
    officialNotificationUrl: 'https://uppsc.up.nic.in',
    officialAdmitCardUrl: 'https://uppsc.up.nic.in',
    sourceUrl: 'https://uppsc.up.nic.in',
    status: 'Released'
  },
  {
    title: 'UPSSSC Preliminary Eligibility Test (PET) 2026 Admit Card',
    organization: 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)',
    category: 'Admit Card',
    state: 'Uttar Pradesh',
    publishDate: '2026-10-18',
    examDate: '2026-10-28 to 2026-10-29',
    shortDescription: 'UPSSSC PET Exam Hall Ticket and District Center allocation slip released on official portal upsssc.gov.in.',
    officialNotificationUrl: 'https://upsssc.gov.in',
    officialAdmitCardUrl: 'https://upsssc.gov.in',
    sourceUrl: 'https://upsssc.gov.in',
    status: 'Released'
  },
  {
    title: 'BPSC 70th Integrated Combined Competitive Prelims Admit Card 2026',
    organization: 'Bihar Public Service Commission (BPSC)',
    category: 'Admit Card',
    state: 'Bihar',
    publishDate: '2026-11-05',
    examDate: '2026-11-17',
    shortDescription: 'Download BPSC 70th CCE Prelims Examination Admit Card with exam center code on onlinebpsc.bihar.gov.in.',
    officialNotificationUrl: 'https://bpsc.bih.nic.in',
    officialAdmitCardUrl: 'https://onlinebpsc.bihar.gov.in',
    sourceUrl: 'https://bpsc.bih.nic.in',
    status: 'Released'
  },
  {
    title: 'Bihar Police Constable Written Examination E-Admit Card 2026',
    organization: 'Central Selection Board of Constable (CSBC) Bihar',
    category: 'Admit Card',
    state: 'Bihar',
    publishDate: '2026-07-28',
    examDate: '2026-08-07 to 2026-08-28',
    shortDescription: 'CSBC Bihar has released the roll number wise admit cards for 21,391 Constable recruitment written examination.',
    officialNotificationUrl: 'https://csbc.bih.nic.in',
    officialAdmitCardUrl: 'https://csbc.bih.nic.in',
    sourceUrl: 'https://csbc.bih.nic.in',
    status: 'Released'
  },
  {
    title: 'DSSSB Various Post Examination Admit Card 2026',
    organization: 'Delhi Subordinate Services Selection Board (DSSSB)',
    category: 'Admit Card',
    state: 'Delhi',
    publishDate: '2026-08-05',
    examDate: '2026-08-12 to 2026-09-05',
    shortDescription: 'Download E-Admit Card for online computer based examination for TGT, PGT, Special Educator and Non-Teaching posts.',
    officialNotificationUrl: 'https://dsssb.delhi.gov.in',
    officialAdmitCardUrl: 'https://dsssbonline.nic.in',
    sourceUrl: 'https://dsssb.delhi.gov.in',
    status: 'Released'
  },
  {
    title: 'Indian Air Force Agniveervayu Phase-1 Online Exam Admit Card 2026',
    organization: 'Indian Air Force (IAF)',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-03-12',
    examDate: '2026-03-17',
    shortDescription: 'Candidate login portal active for downloading Agniveervayu STAR 01/2026 Phase-1 CBT Admit Card.',
    officialNotificationUrl: 'https://agnipathvayu.cdac.in',
    officialAdmitCardUrl: 'https://agnipathvayu.cdac.in',
    sourceUrl: 'https://agnipathvayu.cdac.in',
    status: 'Released'
  },
  {
    title: 'Indian Army Agniveer Common Entrance Exam (CEE) Admit Card 2026',
    organization: 'Join Indian Army',
    category: 'Admit Card',
    state: 'All India',
    publishDate: '2026-04-12',
    examDate: '2026-04-22 to 2026-05-03',
    shortDescription: 'Online CEE Hall Ticket available for Agniveer GD, Technical, Clerk, Tradesmen across all Army Recruiting Offices (ARO).',
    officialNotificationUrl: 'https://joinindianarmy.nic.in',
    officialAdmitCardUrl: 'https://joinindianarmy.nic.in',
    sourceUrl: 'https://joinindianarmy.nic.in',
    status: 'Released'
  },

  // =========================================================================
  // 3. RESULTS / SCORECARDS / SELECTION MERIT LISTS
  // =========================================================================
  {
    title: 'UP Police Constable Direct Recruitment Written Exam Result & Cut-off Marks',
    organization: 'UP Police Recruitment and Promotion Board (UPPRPB)',
    category: 'Result',
    state: 'Uttar Pradesh',
    publishDate: '2026-10-15',
    shortDescription: 'UPPRPB has announced the result and cutoff marks for 60,244 Constable posts. Candidates qualified for Physical Standard Test (PST) and Document Verification can check roll numbers.',
    officialNotificationUrl: 'https://uppbpb.gov.in',
    officialResultUrl: 'https://uppbpb.gov.in',
    sourceUrl: 'https://uppbpb.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC CGL 2026 Final Selection Result, Merit List & Post-Wise Cut-off Marks',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-11-20',
    shortDescription: 'Staff Selection Commission has declared the Final Result of Combined Graduate Level Examination with allocated departments and roll numbers.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialResultUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC GD Constable Written Examination Result & State-Wise Cut-off Percentile',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-07-10',
    shortDescription: 'Result of Computer Based Examination of Constable (GD) in CAPFs, SSF and Rifleman in Assam Rifles for appearing in PET/PST.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialResultUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC CHSL 10+2 Tier-I Marks & Scorecard Declared at ssc.gov.in',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-08-14',
    shortDescription: 'Check individual normalized marks, category-wise cutoff and list of candidates shortlisted for Tier-2 examination.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialResultUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'SSC CPO Sub-Inspector in Delhi Police & CAPFs Final Result 2026',
    organization: 'Staff Selection Commission (SSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-06-30',
    shortDescription: 'Declaration of Final Result for Sub-Inspectors in Delhi Police and CAPFs Examination. Check final appointment list.',
    officialNotificationUrl: 'https://ssc.gov.in',
    officialResultUrl: 'https://ssc.gov.in',
    sourceUrl: 'https://ssc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC Civil Services (IAS / IFS) 2026 Final Selection Result & Toppers List',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-04-16',
    shortDescription: 'UPSC has published the list of successful candidates recommended for appointment to IAS, IFS, IPS and Central Group A & B Services based on CSE Main Exam and Personality Test.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialResultUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC National Defence Academy (NDA & NA-I) Final Result with Marks',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-05-28',
    shortDescription: 'Final merit list of candidates who qualified on the basis of the written examination and SSB interview for NDA 153rd Course.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialResultUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'UPSC Combined Defence Services (CDS-I) Written Examination Result',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-05-20',
    shortDescription: 'Check roll numbers of candidates shortlisted for interview by the Services Selection Board (SSB) of the Ministry of Defence.',
    officialNotificationUrl: 'https://upsc.gov.in',
    officialResultUrl: 'https://upsc.gov.in',
    sourceUrl: 'https://upsc.gov.in',
    status: 'Released'
  },
  {
    title: 'RRB ALP (Assistant Loco Pilot) CBT-1 Scorecard & Cutoff Percentile',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-10-10',
    shortDescription: 'Download normalized scorecard and check zone-wise shortlist for Second Stage CBT Examination for ALP posts.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialResultUrl: 'https://www.rrbapply.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Released'
  },
  {
    title: 'RRB NTPC Final Selection Panel & Document Verification Merit List',
    organization: 'Railway Recruitment Control Board (RRB)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-07-22',
    shortDescription: 'Provisional Part Panel for Station Master, Train Manager and Commercial Clerk published across all RRB divisions.',
    officialNotificationUrl: 'https://rrbcdg.gov.in',
    officialResultUrl: 'https://rrbcdg.gov.in',
    sourceUrl: 'https://indianrailways.gov.in',
    status: 'Released'
  },
  {
    title: 'IBPS PO / Management Trainee Final Combined Allotment Result & Cut-off',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-04-01',
    shortDescription: 'Check bank-wise provisional allotment result and minimum/maximum combined scores for CRP PO/MT under IBPS.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialResultUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'IBPS Clerk Main Examination State-Wise Merit List & Allotment Result',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-04-01',
    shortDescription: 'Provisional allotment under CRP Clerks announced on ibps.in. View state-wise cutoff and allotted bank.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialResultUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'IBPS RRB Officer Scale-I & Office Assistant Final Selection Result',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-01-01',
    shortDescription: 'Final combined result for appointment in 43 Regional Rural Banks declared by IBPS.',
    officialNotificationUrl: 'https://www.ibps.in',
    officialResultUrl: 'https://www.ibps.in',
    sourceUrl: 'https://www.ibps.in',
    status: 'Released'
  },
  {
    title: 'SBI PO Final Selection Result & List of Selected Candidates',
    organization: 'State Bank of India (SBI)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-03-19',
    shortDescription: 'State Bank of India has published the final merit list of candidates selected for appointment as Probationary Officers.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialResultUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Released'
  },
  {
    title: 'SBI Junior Associate (Clerk) Final Selection Result & Waitlist',
    organization: 'State Bank of India (SBI)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-06-27',
    shortDescription: 'Roll numbers of provisionally selected candidates for appointment as Junior Associates in State Bank of India.',
    officialNotificationUrl: 'https://sbi.co.in/web/careers',
    officialResultUrl: 'https://sbi.co.in/web/careers',
    sourceUrl: 'https://sbi.co.in/web/careers',
    status: 'Released'
  },
  {
    title: 'NTA UGC NET Subject-Wise Scorecard, Cut-off Percentile & JRF Award List',
    organization: 'National Testing Agency (NTA)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-09-30',
    shortDescription: 'NTA has released the NTA UGC NET scorecard, subject-wise cutoff percentile, and list of candidates qualified for JRF & Assistant Professor.',
    officialNotificationUrl: 'https://ugcnet.nta.ac.in',
    officialResultUrl: 'https://ugcnet.nta.ac.in',
    sourceUrl: 'https://nta.ac.in',
    status: 'Released'
  },
  {
    title: 'CTET Central Teacher Eligibility Test Marksheet & Eligibility Result',
    organization: 'Central Board of Secondary Education (CBSE)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-07-31',
    shortDescription: 'Check CTET Examination Result by entering Roll Number. Digital marksheet and eligibility certificates issued on DigiLocker.',
    officialNotificationUrl: 'https://ctet.nic.in',
    officialResultUrl: 'https://cbseresults.nic.in',
    sourceUrl: 'https://ctet.nic.in',
    status: 'Released'
  },
  {
    title: 'UPPSC Combined State / Upper Subordinate (PCS) Final Selection Result',
    organization: 'Uttar Pradesh Public Service Commission (UPPSC)',
    category: 'Result',
    state: 'Uttar Pradesh',
    publishDate: '2026-05-15',
    shortDescription: 'UPPSC has declared the final result of PCS examination with selection lists for Deputy Collector, DSP, BDO, Naib Tehsildar.',
    officialNotificationUrl: 'https://uppsc.up.nic.in',
    officialResultUrl: 'https://uppsc.up.nic.in',
    sourceUrl: 'https://uppsc.up.nic.in',
    status: 'Released'
  },
  {
    title: 'UPSSSC Preliminary Eligibility Test (PET) Final Revised Scorecard',
    organization: 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)',
    category: 'Result',
    state: 'Uttar Pradesh',
    publishDate: '2026-01-29',
    shortDescription: 'Download official UPSSSC PET scorecard with raw marks, normalized marks and percentile score valid for one year for all UP Group C recruitments.',
    officialNotificationUrl: 'https://upsssc.gov.in',
    officialResultUrl: 'https://upsssc.gov.in',
    sourceUrl: 'https://upsssc.gov.in',
    status: 'Released'
  },
  {
    title: 'BPSC 69th Integrated Combined Competitive Examination Final Result',
    organization: 'Bihar Public Service Commission (BPSC)',
    category: 'Result',
    state: 'Bihar',
    publishDate: '2026-04-25',
    shortDescription: 'Final result and merit list for Bihar Administrative Service, Bihar Police Service, Financial Administrative Officer published by BPSC.',
    officialNotificationUrl: 'https://bpsc.bih.nic.in',
    officialResultUrl: 'https://bpsc.bih.nic.in',
    sourceUrl: 'https://bpsc.bih.nic.in',
    status: 'Released'
  },
  {
    title: 'Bihar Police Constable Direct Recruitment Final Selection List',
    organization: 'Central Selection Board of Constable (CSBC) Bihar',
    category: 'Result',
    state: 'Bihar',
    publishDate: '2026-11-10',
    shortDescription: 'Final selection list of candidates who qualified written examination, PET (Physical), and document verification for Bihar Police Constable.',
    officialNotificationUrl: 'https://csbc.bih.nic.in',
    officialResultUrl: 'https://csbc.bih.nic.in',
    sourceUrl: 'https://csbc.bih.nic.in',
    status: 'Released'
  },
  {
    title: 'DSSSB Assistant Teacher & TGT Recruitment Final Result & Marks',
    organization: 'Delhi Subordinate Services Selection Board (DSSSB)',
    category: 'Result',
    state: 'Delhi',
    publishDate: '2026-09-12',
    shortDescription: 'Final result and cutoff marks declared for Assistant Teacher (Nursery), TGT Mathematics, English, Social Science in DoE Delhi.',
    officialNotificationUrl: 'https://dsssb.delhi.gov.in',
    officialResultUrl: 'https://dsssb.delhi.gov.in',
    sourceUrl: 'https://dsssb.delhi.gov.in',
    status: 'Released'
  },
  {
    title: 'Indian Air Force Agniveervayu Provisional Select List (PSL) Declared',
    organization: 'Indian Air Force (IAF)',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-05-31',
    shortDescription: 'IAF has published the Provisional Select List (PSL) for Science and Non-Science subject Agniveervayu intakes on agnipathvayu.cdac.in.',
    officialNotificationUrl: 'https://agnipathvayu.cdac.in',
    officialResultUrl: 'https://agnipathvayu.cdac.in',
    sourceUrl: 'https://agnipathvayu.cdac.in',
    status: 'Released'
  },
  {
    title: 'Indian Army Agniveer Common Entrance Exam (CEE) Final Result Declared',
    organization: 'Join Indian Army',
    category: 'Result',
    state: 'All India',
    publishDate: '2026-05-28',
    shortDescription: 'Final merit list and selected candidates list for Agniveer Rally declared zone-wise on joinindianarmy.nic.in.',
    officialNotificationUrl: 'https://joinindianarmy.nic.in',
    officialResultUrl: 'https://joinindianarmy.nic.in',
    sourceUrl: 'https://joinindianarmy.nic.in',
    status: 'Released'
  }
];
